### ISSUE TITLE
Config file observations

### ISSUE THREAD

**Issue by Standaa** [phantombuster/sdk#7]
Hello PB team,
Quick suggestion.
I think it would be much nicer if you could pass the secret upon initializing the library or make it an env variable.

Motivations:
1. Dealing with updating config file secrets in a Dockerfile after loading a vault like Hashicorp or dotenv is clunky
2. Variable leaks into the the docker image config file
3. You cannot commit the config file with the secret. You would have to commit an example config file to avoid devs accidentally comitting the secret. One more thing people have to configure etc.

**Comment by DamienLaf** [comment]
You can use your environment variable in the `apiKey` property by prefixing its name with `ENV:`.
If your environment variable name is `MY_PB_KEY`, you should set it in your config file like this:
```JSON
    "apiKey":"ENV:MY_PB_KEY",
```
